### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by keirlawson** [SystemFw/eidos#1]
Can we have one?

**Comment by SystemFw** [comment]
The fight with Sonatype is on. But yes, it will be out soon.

**Comment by SystemFw** [comment]
Eidos v.0.1 is in sonatype's releases repo, it will be available on Maven Central as soon as sonatype synching is activated (which should be a matter of hours/small number of days)

**Comment by SystemFw** [comment]
Eidos 0.1 is out for scala 2.12 and 2.11

**Comment by keirlawson** [comment]
Great!
